/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F103C6T6.h"
#include "STM32F103C6T6_GPIO_Driver.h"
#include "STM32F103C6T6_EXTI_Driver.h"
#include "STM32F103C6T6_UART_Driver.h"


void clock_init(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

void MOSTAFA_UART_CALLBACK(void);
unsigned short ch;

int main(void)
{
	clock_init();

	USART_Config uart_config;

	uart_config.USART_BaudRate = USART_BaudRate_115200;
	uart_config.USART_FlowCtrl = USART_FlowCtrl_NONE;
	uart_config.USART_IRQ_Enable = USART_IRQ_Enable_RXNEIE_ORE;
	uart_config.USART_IRQ_CallBack_Func = MOSTAFA_UART_CALLBACK;
	uart_config.USART_Parity = USART_Parity_NONE;
	uart_config.USART_WordLength = USART_8_DataBits;
	uart_config.USART_StopBits = USART_StopBits_One;
	uart_config.USART_MODE = USART_MODE_RX_TX;

	MCAL_USART_Init(USART1, &uart_config);
	MCAL_USART_GPIO_Set_Pins(USART1);

	while (1)
	{

	}
}

void MOSTAFA_UART_CALLBACK(void)
{
	MCAL_USART_ReceiveData(USART1, &ch, Polling_Disable);
	MCAL_USART_SendData(USART1, &ch, Polling_Enable);

}






