/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "STM32F103C6T6.h"
#include "STM32F103C6T6_GPIO_Driver.h"

void clock_init(void)
{
	/*Enable Clock For GBIOA and GPIOB*/
	//RCC->APB2ENR |= (0b11<2);

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

void GPIO_init(void)
{
	//Configure PORTA pin1 & pin13 to be Floating Input
	GPIO_PinConfig_t PinCfg;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	PinCfg.GPIO_OUTPUT_SPEED = 0;
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	PinCfg.GPIO_OUTPUT_SPEED = 0;
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	MCAL_GPIO_Init(GPIOA, &PinCfg);


	//Configure PORTB pin1 & pin13 to be Output Push-Pull with 10MHz Speed
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
}

void my_wait(int x)
{
	uint32_t i,j;
	for(i = 0 ; i < x ; i++)
		for(j = 0 ; j < 255 ; j++);
}

int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
			// PA1 is Connected PUR so it's 1 by default
			if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0 ) //Reading 0 means the button is pressed
			{
				MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);	//Toggle PB1
				while (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0); // Single Press: Fix your state by staying in loop if button is pressed
			}
			// PA1 is Connected PDR so it's 0 by default
			if ( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1 ) //Reading 1 means the button is pressed
				MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);	// Multiple Press: Keep Toggling if button is pressed

			my_wait(1);
	}
}
