/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "LCD.h"
#include "Keypad.h"
#include "STM32F103C6T6_GPIO_Driver.h"


void clock_init(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}


int main(void)
{
	clock_init();
	LCD_init();
	KEYPAD_init();
	uint8_t key_char;
	while(1)
	{
		key_char = KEYPAD_get_charcter();
		switch (key_char)
		{
			case 'a':
				//no key pressed
				break;
			case 'c':
				LCD_clear_screen();
				//make counter @ LCD_write_char to be 1
				break;
			default:
				LCD_write_char(key_char);
				break;
		}
	}
	return 0;
}
