/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F103C6T6.h"
#include "STM32F103C6T6_GPIO_Driver.h"
#include "STM32F103C6T6_UART_Driver.h"
#include "STM32F103C6T6_EXTI_Driver.h"
#include "STM32F103C6T6_SPI_Driver.h"

#define MCU_ACT_AS_MASTER
//#define MCU_ACT_AS_SLAVE

void clock_init(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

void MOSTAFA_UART_CALLBACK(void);
void MOSTAFA_SPI_CALLBACK(SPI_Interrupt interrupt_src);

unsigned short ch;

int main(void)
{
	clock_init();

	USART_Config uart_config;

	uart_config.USART_BaudRate = USART_BaudRate_115200;
	uart_config.USART_FlowCtrl = USART_FlowCtrl_NONE;
	uart_config.USART_IRQ_Enable = USART_IRQ_Enable_RXNEIE_ORE;
	uart_config.USART_IRQ_CallBack_Func = MOSTAFA_UART_CALLBACK;
	uart_config.USART_Parity = USART_Parity_NONE;
	uart_config.USART_WordLength = USART_8_DataBits;
	uart_config.USART_StopBits = USART_StopBits_One;
	uart_config.USART_MODE = USART_MODE_RX_TX;

	MCAL_USART_Init(USART1, &uart_config);
	MCAL_USART_GPIO_Set_Pins(USART1);

	SPI_Config config_spi;

	config_spi.Clk_Phase = SPI_Clk_Phase_Second;
	config_spi.Clk_Polarity = SPI_Clk_Polarity_High;
	config_spi.Data_Size = SPI_Data_Size_8Bits;
	config_spi.Bit_Orientation = SPI_Orientation_MSB_First;
	config_spi.BaudRate_Prescaler = SPI_BaudRate_Prescaler_8; //Assume SPI is 8Mhz
	config_spi.Communication_MODE = SPI_Directional_2Lines;

#ifdef MCU_ACT_AS_MASTER
	config_spi.Device_MODE = SPI_Device_MODE_MASTER;
	config_spi.IRQ_Enable = SPI_IRQ_NONE;
	config_spi.NSS = SPI_NSS_SW_SET;	//Make NSS of Master Idle state High and I will reset it @ sending
	config_spi.PTR_IRQ_CallBack = NULL;
#endif

#ifdef MCU_ACT_AS_SLAVE
	config_spi.Device_MODE = SPI_Device_MODE_SLAVE;
	config_spi.IRQ_Enable = SPI_IRQ_RXNEIE_Enable;
	config_spi.NSS = SPI_NSS_HW_Output_Disable;
	config_spi.PTR_IRQ_CallBack = MOSTAFA_SPI_CALLBACK;
#endif

	MCAL_SPI_Init(SPI1, &config_spi);
	MCAL_SPI_GPIO_Set_Pins(SPI1);

	//As NSS is SW controlled so this is a configuration for GPIO PA4 for it.


#ifdef MCU_ACT_AS_MASTER
	GPIO_PinConfig_t SPI_SW_pin_config;
	SPI_SW_pin_config.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	SPI_SW_pin_config.GPIO_OUTPUT_SPEED = GPIO_OUTPUT_SPEED_10MHz;
	SPI_SW_pin_config.GPIO_PinNumber = GPIO_PIN_4;
	MCAL_GPIO_Init(GPIOA, &SPI_SW_pin_config);

	//Set it high by default
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);
#endif

	while (1)
	{

	}
}

void MOSTAFA_UART_CALLBACK(void)
{
#ifdef MCU_ACT_AS_MASTER
	MCAL_USART_ReceiveData(USART1, &ch, USART_Polling_Disable);
	MCAL_USART_SendData(USART1, &ch, USART_Polling_Enable);

	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_RESET); //NSS --> LOW to Select Slave
	MCAL_SPI_TX_RX(SPI1, &ch, SPI_Polling_Enable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);   //NSS --> Return It High
#endif
}

void MOSTAFA_SPI_CALLBACK(SPI_Interrupt interrupt_src)
{
#ifdef MCU_ACT_AS_SLAVE
	if(interrupt_src.RXNE)
	{
		ch = 0xF;
		MCAL_SPI_TX_RX(SPI1, &ch, SPI_Polling_Disable);
		MCAL_USART_SendData(USART1, &ch, USART_Polling_Enable);
	}
#endif
}
