/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

// register address
#define RCC_BASE	0x40021000
#define GPIOA_BASE 	0x40010800
#define EXTI_BASE 	0x40010400
#define AFIO_BASE 	0x40010000
#define NVIC_BASE	0xE000E000

#define NVIC_EXTI 		*(volatile uint32_t*)(NVIC_BASE + 0x100)
#define AFIO_EXTICR1	*(volatile uint32_t*)(AFIO_BASE + 0x08)
#define EXTI_IMR 		*(volatile uint32_t*)(EXTI_BASE + 0x00)
#define EXTI_EMR 		*(volatile uint32_t*)(EXTI_BASE + 0x04)
#define EXTI_RTSR 		*(volatile uint32_t*)(EXTI_BASE + 0x08)
#define EXTI_FTSR 		*(volatile uint32_t*)(EXTI_BASE + 0x0C)
#define EXTI_SWIER	 	*(volatile uint32_t*)(EXTI_BASE + 0x10)
#define EXTI_PR 		*(volatile uint32_t*)(EXTI_BASE + 0x14)

#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)



void init_EXTI(void)
{
	//Enable External interrupt for PA0 by configure  register AFIO_EXTICR1
	AFIO_EXTICR1 &= ~(0xF << 0);
	AFIO_EXTICR1 |= (0b0000 << 0);

	//Enable Rising trigger selection register bit 0 corresponding to EXTI0
	EXTI_RTSR |= (1 << 0);

	//Enable Interrupt mask register bit 0 corresponding to EXTI0
	EXTI_IMR |= (1 << 0);

	//Enable Failing trigger selection register bit 0 corresponding to EXTI0
	//EXTI_FTSR |= (1 << 0);

	//Enable NVIC IRQ6 which 0 corresponding to EXTI0
	NVIC_EXTI |= (1 << 6);
}


void EXTI0_IRQHandler(void)
{
	//Toggling LED
	GPIOA_ODR ^= (1<<13) ;

	//Clear Pending RequesEXTI_PR by set bit 0 which is corresponding to EXTI0
	EXTI_PR |= (1 << 0);
}


void clock_init(void)
{
	//Enable PortA Clock for
	RCC_APB2ENR |= (1<<2);

	//Enable AFIO Clock
	RCC_APB2ENR |= (1<<0);

}

void gpio_init(void)
{
	//Init GPIOA for LED
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	//Init GPIO_PA0 for Switch MODE0 = 00 CNF0 = 01 "Floating input"
	GPIOA_CRL &= (0b0000 << 0);
	GPIOA_CRL |= (0b0100 << 0);
}


int main(void)
{
	clock_init();
	gpio_init();
	init_EXTI();

	while(1)
	{

	}
	return 0;
}
