/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// register address
#define RCC_BASE 	0x40021000
#define GPIOA_BASE 	0x40010800
#define RCC_CR *(volatile uint32_t *)(RCC_BASE + 0x00)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)

void init_clock(void)
{
	//Enable HSI_RC
	RCC_CR |= (1<<0);
	while(!(RCC_CR & 0x2)); //wait for enable

	//System clock switch
	RCC_CFGR &= (0b00);
	while(RCC_CFGR & 0x0C); //wait for enable

	//APB1 Bus frequency 4MHZ
	RCC_CFGR &= ~(0b000 << 8);
	RCC_CFGR |= (0b100 << 8);

	//APB2 Bus frequency 2MHZ
	RCC_CFGR &= ~(0b000 << 11);
	RCC_CFGR |= (0b101 << 11);

	//AHB  Bus frequency 8MHZ
	RCC_CFGR &= ~(0xF << 4);

}

int main(void)
{
	init_clock();
	// Enable APB2ENR Bus
	RCC_APB2ENR |= (1<<2);
	//Init GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
			GPIOA_ODR &= ~(1<<13) ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
	}
}
