/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "platform_types.h"
#include "stdlib.h"

#define RCC_BASE 0x40021000
#define APB2ENR_OFFSET 0x18
#define GPIOA_BASE 0x40010800
#define CRH_OFFSET 0x04
#define ODR_OFFSET 0x0C

#define RCC *(vuint32_t*)(RCC_BASE + APB2ENR_OFFSET)
#define CRH *(vuint32_t*)(GPIOA_BASE + CRH_OFFSET)
#define ODR *(vuint32_t*)(GPIOA_BASE + ODR_OFFSET)

typedef union{
	vuint32_t all_data_bits;
	struct {
		vuint32_t reserved:13; // from bit 0 -> 12
		vuint32_t pin13:1;
	}pins;
}U_ODR;

volatile U_ODR *R_ODR = (volatile U_ODR *)(GPIOA_BASE + ODR_OFFSET);


uint8 g_variables[3] = {1,2,3};
uint8 const const_variables[3] = {1,2,3};
vuint8_t bss_var[3];

extern uint32 _heap_End;
void *_sbrk(int incr)
{
	static uint8 *heap_ptr = NULL; //Static to avoid erase it's value when exit the scoop
	static uint8 *prev_heap_ptr = NULL;
	extern uint32 _E_bss;
	extern uint32 _heap_End;

	//First time initializing heap start point
	if(heap_ptr == NULL)
		heap_ptr = (uint8*)&_E_bss;
	
	/* store the start point address of allocated
	 data to be returned and used to store data */
	prev_heap_ptr = heap_ptr;

	/* Safety condition if allocation exceed heap size */
	if ((heap_ptr + incr) > ((uint8*)&_heap_End) )
		return (void*)NULL;

	heap_ptr = heap_ptr + incr; //Allocation required memory
	return (void*)prev_heap_ptr;
}

int main ()
{
	int *ptr = (int*)malloc(4);

	RCC |= (1<<2);      // Enable Clock
	CRH &= 0xff0fffff;  // set bit 20 -> 24 to 0
	CRH |= (1<<21);     // Make it OUTPUT

	while (1)
	{
//		ODR &= ~(1<<13); // Clear using bit filed
		R_ODR->pins.pin13 = 0; // Clear using structure register mapping
		for (uint16 i = 0 ; i < 5000 ; i++); // Delay

//		ODR |= (1<<13); // set using bit filed
		R_ODR->pins.pin13 = 1; //set using structure register mapping
		for (uint16 i = 0 ; i < 5000 ; i++);

	}
	free(ptr);
	return 0;
}